apiVersion: 1

datasources:
  - name: THQ-Postgres
    type: postgres
    access: proxy
    url: db:5432
    database: thq
    user: thq
    secureJsonData:
      password: thq
    jsonData:
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    isDefault: true
    editable: true
